name: matrix demo
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]
                operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build